// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCD383MXpbZ54c8ITC3B4rHwAfZPPpM2x8',
    appId: '1:227809442243:web:2b4705c7b85185556ba576',
    messagingSenderId: '227809442243',
    projectId: 'ecoquest-game',
    authDomain: 'ecoquest-game.firebaseapp.com',
    storageBucket: 'ecoquest-game.appspot.com',
    measurementId: 'G-F9ZLQ8X4J9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6FiYHNwzvEq3Hhiy1uzbRVf-hlWfFIkQ',
    appId: '1:227809442243:android:4036c8077ac8403b6ba576',
    messagingSenderId: '227809442243',
    projectId: 'ecoquest-game',
    storageBucket: 'ecoquest-game.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcQSSuPwK0WSrXxY4tqkcZrL6nhCSbc_c',
    appId: '1:227809442243:ios:8179b198a6af698a6ba576',
    messagingSenderId: '227809442243',
    projectId: 'ecoquest-game',
    storageBucket: 'ecoquest-game.appspot.com',
    iosBundleId: 'com.appventor.ecoquest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBcQSSuPwK0WSrXxY4tqkcZrL6nhCSbc_c',
    appId: '1:227809442243:ios:64ff73a8aed7a3846ba576',
    messagingSenderId: '227809442243',
    projectId: 'ecoquest-game',
    storageBucket: 'ecoquest-game.appspot.com',
    iosBundleId: 'com.appventor.ecoquest.RunnerTests',
  );
}
